### ISSUE TITLE
Add pre-built files to browser/dist folder?

### ISSUE THREAD

**Issue by jamiegaines** [basti1302/traverson-hal#1]
Hello.

I'm trying to use traverson-angular as a HAL client via bower for an angular project.  When I bower install the traverson-hal package, the traverson-hal.js files are not located in the browser/dist folder like you did for traverson-angular.

Would it be possible for you to add the pre-built files to traverson-hal like you did for traverson-angular?  It makes it so much easier to use if you can just download the package and go.

Thanks!

**Comment by basti1302** [comment]
Actually traverson-hal has not been released yet. I will do so in the next few days and then the pre-built files will be in browser/dist as usual. Also note that traverson 1.0.0 which adds support for media type plug-ins (like traverson-hal) has not yet been released. Give me a few more days please.

**Comment by basti1302** [comment]
traverson-hal 1.0.0 has been released via npm and bower.
