### ISSUE TITLE
Problems with tests in PhantomJS

### ISSUE THREAD

**Issue by osvaldopina** [basti1302/traverson-hal#12]
Hi,

I´m creating tests for a hal application using karma, jasmine and sinon. It works fine using Chrome as browser but when I change to Phantom the following exception appears:
```javascript
PhantomJS 1.9.8 (Windows 7 0.0.0) Grid Get data FAILED
        TypeError: 'undefined' is not a function (evaluating 'abortTraversal.bind(traversalState)')
            at createInitialTraversalState (D:/git/repository/grd/testes-aceitacao/node_modules/traverson/browser/dist/traverson.js:985)
            at getResource (D:/git/repository/grd/testes-aceitacao/node_modules/traverson/browser/dist/traverson.js:893)
            at D:/git/repository/grd/testes-aceitacao/src/test/js/testes-aceitacao-spec.js:19

```
```javascript
The scripts that I include in the tests are:

        'node_modules/jquery/dist/jquery.js',
        'node_modules/traverson/browser/dist/traverson.js',
        'node_modules/traverson/browser/dist/traverson.external.js',
        'node_modules/traverson-hal/browser/dist/traverson-hal.js',
        'node_modules/traverson-hal/browser/dist/traverson-hal.external.js'
```
Did I miss something?

**Comment by basti1302** [comment]
First, you should not include traverson.js *and* traverson.external.js. Same goes for traverson-hal.js and traverson-hal.external.js. For each pair, use only one. Have a look at https://github.com/basti1302/traverson/blob/master/user-guide.markdown#browser.

If you are not using browserify (I guess you are not) than the files **without external** are what you want.

Not sure if this is related to your problem. Do you have the complete repo in a public place? Then I could take a look what's wrong. It's really hard to tell from what you posted. I don't know what `abortTraversal` is. Is it a function? Or an object? Is it even supposed to have a bind method?

**Comment by osvaldopina** [comment]
Sorry, I think I opened an issue in the wrong project. Should have been be traverson. I will setup a public project and open the issue in the correct project.
