### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by mimol91** [basti1302/traverson-hal#21]
I am using traverson for a while.
Recently I've noticed that there is no way to detect if error during request is from traverson or traverson-hal. Moreover it returns only plain message, without any error type.
Like in https://github.com/basti1302/traverson-hal/blob/master/index.js#L64
I need to know if its a `linkError` or `embeddedError` (For example link to resource is not in server response)
Currently I can only parse strings, but it would be much more convenient to get error type, either by 
create own `Error` types, 
pass to `Error` object instead string
or just add `ctx` as 2nd argument of `Error`

**Comment by basti1302** [comment]
This sounds like a good idea. However, I'd like to thoroughly understand your use case and the requirements here. Could you paste a code snippet of the part where you are using traverson/traverson-hal. You probably have some kind of if statement that does different things depending on the kind of error, I would like to see that, if possible.

**Comment by mimol91** [comment]
Hey.
Thanks for response.

It is taken form Traverson Readme
```
  traverson
    .from('http://api.io')
    .jsonHal()
    .follow('ht:me', 'ht:posts')
    .getResource(function(error, document) {
      if (error) {
        console.error(error.name)
      }
    });
```
I can get error type - which is `JSONError` 
https://github.com/basti1302/traverson/blob/0fd4f349e2bf007ea8440284e3e1e252f08e7ae1/lib/transforms/parse.js  - so its really great.

I've also tried
```
  traverson
    .from('http://haltalk.herokuapp.com/')
    .jsonHal()
    .follow('ht:me')
    .getResource(function(error, document) {
      if (error) {
        console.log(error.name);
      }
    });
```
error.name -  `HTTPError`, becauses erver status code = `500`


**The problem is with**
```
  traverson
    .from('http://api.opensupporter.org/api/v1/')
    .jsonHal()
    .follow('self', 'invalid_link')
    .getResource(function(error, document) {
      if (error) {
        console.log(error.name);
      }
    });
```
`error.name` is just 'error' https://github.com/basti1302/traverson-hal/blob/master/index.js#L64 

I would like to know what type of error it is. (like linkMissing), and some other errors for `ctx.linkError` or `ctx.embeddedError`.
I need to be able to detect if there is no link which I want to traverse (`invalid_link`) in server response

**Comment by basti1302** [comment]
Thanks for the code snippets. That's not exactly what I meant, though. What I am interested in is what you are going to do, depending on various error types. How does you code handle these different errors? You surely do not want to differentiate between them just to call `console.log` right?

**Comment by mimol91** [comment]
Sure.
Basically I want to distinguish at least to types:
- When server status code >= 300 I want to display modal which says that something goes wrong and user need to refresh page
- If link is missing, I need to set catch it and set result as empty array (I m using redux, and API do not return links if collection is empty)

**Comment by mimol91** [comment]
@basti1302 Should I prepare PR for that?

**Comment by basti1302** [comment]
Yes, that would be welcome!

**Comment by mimol91** [comment]
@basti1302 
Could you do CodeReview for https://github.com/basti1302/traverson-hal/pull/22 ?

**Comment by basti1302** [comment]
Sure, I'll probably can get it done tomorrow. A little more patience :)

**Comment by mimol91** [comment]
Thanks for merging.
I will close this issue,

**Comment by basti1302** [comment]
This has been released with version 5.0.0.

**Comment by basti1302** [comment]
From the release notes, for reference: All `Error` objects created by Traverson and traverson-hal now have the `name` property set, see [Traverson API docs on error names](https://github.com/basti1302/traverson/blob/master/api.markdown#traverson-errors) and [traverson-hal docs on error names](#errors). ([#21](https://github.com/basti1302/traverson-hal/issues/21) and [#22](https://github.com/basti1302/traverson-hal/issues/22), thanks to @mimol91)

**Comment by basti1302** [comment]
Btw, thanks for the PR over in #22 and bringing the issue up in general. After merging your changes I extended them to the whole codebase. You might want to check out [this commit in traverson-hal](https://github.com/basti1302/traverson-hal/commit/d7105772b704c4d7b42dd05bcfa17ea23404cb80) and [this commit in traverson](https://github.com/basti1302/traverson/commit/9f4b98ce8e280f4c2f99516b6e3f9ef0e953435a) to see if it still fits your requirements (it should, I think). 

Also, [this comment](https://github.com/basti1302/traverson-hal/commit/d7105772b704c4d7b42dd05bcfa17ea23404cb80#diff-168726dbe96b3ce427e7fedce31bb0bcR85) might be relevant for your use case (depends on your hal documents).
