### ISSUE TITLE
Prefer embedded resources over links

### ISSUE THREAD

**Issue by maherm** [basti1302/traverson-hal#5]
Hi there,
the [RFC Draft for HAL](https://tools.ietf.org/html/draft-kelly-json-hal-06) defines something called ***Hypertext Cache Pattern***:

>The "hypertext cache pattern" allows servers to use embedded
resources to dynamically reduce the number of requests a client
makes, improving the efficiency and performance of the application.
>
>Clients MAY be automated for this purpose so that, for any given link
  relation, they will read from an embedded resource (if present) in
  preference to traversing a link.
>
  >To activate this client behaviour for a given link, servers SHOULD
  add an embedded resource into the representation with the same
   relation.

So, basically it says, that if there is an embedded resource and a linked resource with the same name, the client may try to use the embedded resource. This is the exact opposite of the current behavior of traverson-hal. I think, there should be at least the option to enable this behavior. I understand your reasoning there: you can only be sure to have the whole resource when accessing the link. But it also undermines the idea of HAL's *Hypertext Cache Pattern*.

Since changing the default behaviour of the plugin would be an unnecessary breaking change, I see two solutions here:
1.  Use the embedded resource and fall back to the linked one if an unknown relation is queried. 
I think, this would be the nicer solution, but I don't know how much work this would need.
2. Add a boolean flag to enable the "embedded first" behavior.
The advantage of this one is, that it's a quick fix and should satisfy anybody who needs "embedded first" (like me ;) )

Let me know what you think.

**Comment by basti1302** [comment]
Yes, sounds reasonable.

I think option 1. opens up a lot of edge cases and makes thinks really complicated. I'd rather not go down that route unless there are very compelling reasons.

I'm sold on 2., so we make it configurable. The only thing I'm not sure about is the default value. 

I do not really think that the problem of breaking change is a strong argument here, we just up the major version digit and that's fine. I would rather align the default value with the spec. Only problem here is, the spec is relatively vague in this aspect. A client MAY be automated for this purpose, hmmm.

So what do you think, should "link first" or "embedded first" be the default for this new config option?

**Comment by maherm** [comment]
Since making "embedded first" default might yield unexpected results in some cases, like follow() not working even if the relation is there, i think it would be best to leave "link first" the default option.

**Comment by basti1302** [comment]
Okay, sounds plausible.

**Comment by basti1302** [comment]
This has landed in 1.2.0
