### ISSUE TITLE
inconsistency between readme and actual behavior for follow of embedded resource

### ISSUE THREAD

**Issue by travi** [basti1302/traverson-hal#8]
In the [embedded documents](https://github.com/basti1302/traverson-hal#embedded-documents) section of the readme, it is mentioned that a secondary key and value can be used to follow the link for a resource in a list under the `_embedded` section. 

However, I am experiencing two problems with this.
 * The secondary key and value are being ignored when returning the value from the list and the first item is returned from the list rather than the matched resource. I traced through the code and found that this is consistent with what the [code](https://github.com/basti1302/traverson-hal/blob/master/index.js#L218L221) describes. Am I missing something here, or is the behavior for this still incomplete?
 * It appears to be defaulting to returning the resource directly from the embed rather than following the link and requesting the resource directly from the api, even though I have not specified to `preferEmbeddedResources()`. The embedded resources from this api are usually summary level and require the resource to be requested directly in order to get all of the data. Is the default is `2.0.0` now to prefer embedded rather than following the link?

**Comment by basti1302** [comment]
Yes, from the code (and the tests) I would guess that indeed a secondary key like `ht:post[name:foo]` would not work, only a positional index, that is, `ht:post[1]`.

I'll investigate a bit more and also have a look at your pull request.

**Comment by basti1302** [comment]
Ah, also, preferEmbeddedResources is not the default, so this second things sounds like a bug. It might not be related to selecting an embedded by secondary key. Could you file a new issue for that?

**Comment by basti1302** [comment]
The issue about selecting embedded docs by secondary key should be fixed now.

**Comment by basti1302** [comment]
Fix published in version 2.0.1

**Comment by travi** [comment]
Awesome. Thanks for the quick turn around. I'll try to pull it down tonight and check things out. I'll also try to figure out some better steps to reproduce the embedded vs following issue and get that logged with some more detail.
